version: 2
project_name: vanta-exporter

builds:
  - main: .
    binary: vanta-exporter
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ethanolivertroy
    name: vanta-go-export

brews:
  - repository:
      owner: ethanolivertroy
      name: homebrew-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ethanolivertroy/vanta-go-export"
    description: "CLI tool to export Vanta audit evidence organized by control"
    license: "MIT"
    install: |
      bin.install "vanta-exporter"
    test: |
      assert_match "vanta", shell_output("#{bin}/vanta-exporter --help 2>&1", 2)

scoops:
  - repository:
      owner: ethanolivertroy
      name: scoop-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: bucket
    homepage: "https://github.com/ethanolivertroy/vanta-go-export"
    description: "CLI tool to export Vanta audit evidence organized by control"
    license: "MIT"
